services:
  fith-postgres:
    image: postgres:15-alpine
    container_name: fith_database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - fith_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  fith_pgdata: